name: Update forecast

on:
  schedule:
    - cron: '0 */3 * * *'   # every 3 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate forecast.json
        run: |
          python3 --version
          python3 check_spots.py

      - name: Commit forecast.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add forecast.json
          git commit -m "Update forecast.json [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: git push
